### ISSUE TITLE
[feat] remove code

### ISSUE THREAD

**Issue by luisdemarchi** [albertas/deadcode#2]
@albertas I would like to know if it is possible or if there is a way for me to automatically delete this indicated code?

**Comment by albertas** [comment]
Nope, this feature is not yet implemented. Added it to TODO list.

**Comment by luisdemarchi** [comment]
@albertas I'm impressed with how quickly you respond. Thanks for that and thanks for the lib which in my initial tests is actually superior to the vulture lib.

PS: This feat will be fundamental in my AWS Lambda project

**Comment by albertas** [comment]
> @albertas I'm impressed with how quickly you respond. Thanks for that and thanks for the lib which in my initial tests is actually superior to the vulture lib.
> 
> PS: This feat will be fundamental in my AWS Lambda project

It was a coincidence that I managed to respond so quickly.

Actually `vulture` is way better than this package. I tried to improve my package and bumped into several unhandled edge-cases, which are perfectly covered by vulture. I have created this package by mistake, because I didnt understand how great vulture is. More flexibility could be added to vulture to suppress false-positives, but its dead code detection mechanism works wonders.

**Comment by luisdemarchi** [comment]
@albertas  how complex can it be to create automatic removal? Do you have a "roadmap" of what I need to study/analyze?

**Comment by luisdemarchi** [comment]
Rephrasing the question, do you have any idea of a library that I need to integrate into your code? That I can study and try to implement

**Comment by albertas** [comment]
> Rephrasing the question, do you have any idea of a library that I need to integrate into your code? That I can study and try to implement

Nope, I dont know any libraries which could help with this. However, it might be pretty straightforward to implement it for global variables. I'll try to implement it.

I am planning to integrate some of vultures code later on to cover more unused code cases, which might complicate auto fixing.

**Comment by albertas** [comment]
> I am planning to integrate some of vultures code later on to cover more unused code cases, which might complicate auto fixing.

I have integrated core from `vulture` and added `--fix` option.
