### ISSUE TITLE
Always True ifs are removed

### ISSUE THREAD

**Issue by b-v** [albertas/deadcode#3]
Nice package. I did run into the following problem. When I try to run deadcode --fix on the following
```
a=0
if True:
    a=1
    print(a)

print(a)
```
then it changes it to
```
a=0
print(a)
```

The expected behaviour would be
```
a=0
a=1
print(a)
print(a)
```
or just leaving the `if` intact.

**Comment by albertas** [comment]
Thank you for reporting this bug.

I have disabled unreachable code detection and fixing in `deadcode==2.2.1`. I will put this feature request into my backlog.
